version: '3.8'
services:
  sample:
    # esta linha resolve o problema do container não fechar
    # this line solve the problem of container closing
    stdin_open: true
    container_name: react-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
