version: '3.7'

services:
  sample-prod:
    # linha para solucionar problema com react
    stdin_open: true
    container_name: sample-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
